name: stacks
owner: avowinkel
remote_repository_url: https://github.com/kaktus42/galaxytools/tree/master/tools/stacks
homepage_url: http://catchenlab.life.illinois.edu/stacks
description: Contains the version 1.32 of Stacks (only process_radtags)
long_description: |
  Stacks is a software pipeline for building loci from short-read sequences, such as those generated on the Illumina platform. Stacks was developed to work with restriction enzyme-based data, such as RAD-seq, for the purpose of building genetic maps and conducting population genomics and phylogeography.
  Repository-Maintainer: Alexander Vowinkel
  Repository-Development: https://github.com/kaktus42/galaxytools
type: unrestricted
categories:
- Fasta Manipulation
- Fastq Manipulation
- Genome-Wide Association Study
- Sequence Analysis
- Variant Analysis
